/**
 * Generates the PWA icons and the default boat hero image.
 *
 *   node scripts/generate-assets.mjs
 *
 * The hero is a placeholder: replace public/images/boat-hero.jpg, or upload a
 * real photo to the `media` bucket and set boats.photo_path.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const root = path.resolve(import.meta.dirname, "..");
const iconsDir = path.join(root, "public", "icons");
const imagesDir = path.join(root, "public", "images");

const HULL = "#0a1a2a";
const TEAL = "#2ed3c6";

/** Anchor mark, drawn on a rounded navy tile. `inset` carves the maskable safe zone. */
const anchorIcon = (size, inset = 0) => {
  const pad = size * inset;
  const inner = size - pad * 2;
  return `
<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" rx="${inset > 0 ? 0 : size * 0.22}" fill="${HULL}"/>
  <g transform="translate(${pad} ${pad}) scale(${inner / 512})">
    <g stroke="${TEAL}" stroke-width="30" fill="none" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="256" cy="112" r="36"/>
      <path d="M256 148 V 404"/>
      <path d="M168 212 H 344"/>
      <path d="M120 292 C 120 378 182 428 256 428 C 330 428 392 378 392 292"/>
      <path d="M120 292 L 78 316 M120 292 L 160 312"/>
      <path d="M392 292 L 434 316 M392 292 L 352 312"/>
    </g>
  </g>
</svg>`;
};

/** Dusk seascape with a sailboat silhouette — matches the app's palette. */
const hero = (w, h) => `
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="#071627"/>
      <stop offset="42%"  stop-color="#14344f"/>
      <stop offset="68%"  stop-color="#3f5f70"/>
      <stop offset="82%"  stop-color="#c98b52"/>
      <stop offset="92%"  stop-color="#e8b071"/>
    </linearGradient>
    <linearGradient id="sea" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="#d9a067"/>
      <stop offset="18%"  stop-color="#2c5064"/>
      <stop offset="100%" stop-color="#0a1c2c"/>
    </linearGradient>
    <radialGradient id="sun" cx="0.68" cy="0.9" r="0.42">
      <stop offset="0%"   stop-color="#ffd9a0" stop-opacity="0.95"/>
      <stop offset="55%"  stop-color="#e8a95f" stop-opacity="0.25"/>
      <stop offset="100%" stop-color="#e8a95f" stop-opacity="0"/>
    </radialGradient>
  </defs>

  <rect width="${w}" height="${h}" fill="url(#sky)"/>
  <rect width="${w}" height="${h * 0.72}" fill="url(#sun)"/>
  <rect y="${h * 0.7}" width="${w}" height="${h * 0.3}" fill="url(#sea)"/>

  <!-- sun reflection on the water -->
  <g fill="#f0c084" opacity="0.35">
    <rect x="${w * 0.6}" y="${h * 0.73}" width="${w * 0.16}" height="3" rx="1.5"/>
    <rect x="${w * 0.63}" y="${h * 0.78}" width="${w * 0.1}" height="3" rx="1.5"/>
    <rect x="${w * 0.61}" y="${h * 0.84}" width="${w * 0.14}" height="3" rx="1.5"/>
    <rect x="${w * 0.65}" y="${h * 0.9}" width="${w * 0.07}" height="3" rx="1.5"/>
  </g>

  <!-- sailboat silhouette -->
  <g transform="translate(${w * 0.3} ${h * 0.7})" fill="#061019">
    <path d="M0 0 L0 -${h * 0.44} L${w * 0.115} -${h * 0.03} Z"/>
    <path d="M-${w * 0.012} -${h * 0.02} L-${w * 0.095} -${h * 0.02} L-${w * 0.012} -${h * 0.38} Z"/>
    <path d="M-${w * 0.13} 0 L${w * 0.14} 0 L${w * 0.105} ${h * 0.035} L-${w * 0.1} ${h * 0.035} Z"/>
  </g>
</svg>`;

await mkdir(iconsDir, { recursive: true });
await mkdir(imagesDir, { recursive: true });

const png = (svg, size, file) =>
  sharp(Buffer.from(svg)).resize(size, size).png().toFile(path.join(iconsDir, file));

await png(anchorIcon(512), 192, "icon-192.png");
await png(anchorIcon(512), 512, "icon-512.png");
await png(anchorIcon(512, 0.14), 512, "icon-maskable-512.png");
await png(anchorIcon(512), 180, "apple-touch-icon.png");

await sharp(Buffer.from(anchorIcon(512)))
  .resize(32, 32)
  .png()
  .toFile(path.join(root, "src", "app", "icon.png"));

// Landscape for the home card (4:3), portrait for the full-bleed login screen.
// Cropping the landscape one to portrait cuts the hull off, so it gets its own
// composition rather than an object-position hack.
await sharp(Buffer.from(hero(1400, 1000)))
  .jpeg({ quality: 86, mozjpeg: true })
  .toFile(path.join(imagesDir, "boat-hero.jpg"));

await sharp(Buffer.from(hero(900, 1500)))
  .jpeg({ quality: 86, mozjpeg: true })
  .toFile(path.join(imagesDir, "boat-hero-portrait.jpg"));

// Tiny blurred version used as the Image placeholder while the hero loads.
const blur = await sharp(Buffer.from(hero(1400, 1000)))
  .resize(16)
  .jpeg({ quality: 40 })
  .toBuffer();
await writeFile(
  path.join(root, "src", "lib", "hero-blur.ts"),
  `// Generated by scripts/generate-assets.mjs — do not edit by hand.\n` +
    `export const HERO_BLUR_DATA_URL =\n  "data:image/jpeg;base64,${blur.toString("base64")}";\n`,
);

console.log("Generated icons, hero image and blur placeholder.");
